# Generated by Django 4.2.10 on 2024-02-27 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
